### ISSUE TITLE
Not working in project folder.

### ISSUE THREAD

**Issue by gcphost** [iulian-radu-at/fix-relative-imports-to-baseurl#1]
Hey there,

Thanks for the plugin, this will be a huge time saver. However it is not working in a project folder, likely not locating the tsconfig. If I open the folder outside of the project it works as desired.

Would love for this to work in project folders but happy for what I get now :D Thanks again.

**Comment by iulianraduat** [comment]
Hi @gcphost,

Happy to read that I could help :)
Can you create a minimal repo for reproducing this problem? Or some steps?
If I can reproduce it then a fix will come.

Cheers,
Iulian

**Comment by iulianraduat** [comment]
Hi @gcphost,

Can you please enable the debugging for this extension and check were it is looked for the tsconfig.json?
Please do this for both cases and let me know the results.

Thanks,
Iulian

**Comment by iulianraduat** [comment]
Closed as the reporter did not responded.
