### ISSUE TITLE
Option to fix to shortest instead of always absolute

### ISSUE THREAD

**Issue by neotrow** [iulian-radu-at/fix-relative-imports-to-baseurl#2]
Hey there,

Thanks for the great extension, love it! 

Is there a chance that we could get an option to convert the imports to the shortest instead of always strictly the absolute? 

Basically would be looking for those options:
![image](https://github.com/iulian-radu-at/fix-relative-imports-to-baseurl/assets/92933708/7955f2d8-4444-4278-afe1-dddb767f93ba)

Cheers

**Comment by iulianraduat** [comment]
Hi @neotrow,

This qualify as a subject for a different extension.

I think that maybe in your case will make more sense to use 
```json
{
  "compilerOptions": {
    "paths": {
        "@/*": ["./src/*"],
    },
}
```

See [Paths in tsconfig.json](https://www.typescriptlang.org/tsconfig#paths)

Cheers,
Iulian
